name: fl_country_code_picker
description: A Flutter package for showing a modal that contains country dial code. The user can also search for the available codes and select right from the modal.
version: 0.0.4
homepage: https://github.com/fernan542/fl_country_code_picker

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0
  

flutter:
  assets:
    - assets/flags/